SUPPLIERS = {
    "supplier1": {
        "label": "Velozapchasti",
        "parser": "supplier1",
        "sheet_name": "Sheet1",
        "header_row": 7,
        "article_col": "Артикул",
        "name_col": "Наименование товара",
        "unit_col": "Ед.",
        "pack_col": "в уп",
        "price_col": "цена",
        "photo_col": "фото",
    },
    "supplier2": {
        "label": "Форвард СПб",
        "parser": "supplier2",
        "sheet_name": "Лист_1",
        "header_row": 5,
        "article_col": "Артикул",
        "name_col": "Номенклатура",
        "stock_col": "Остаток, шт.",
        "price_col": "Цена Опт 1, руб.",
        "price_opt2_col": "Цена Опт 2, руб.",
        "price_opt3_col": "Цена Опт 3, руб.",
        "price_rrc_col": "Цена РРЦ, руб.",
    },
    "supplier3": {
        "label": "Колхозник/Монстр",
        "parser": "supplier3",
        "sheet_name": "Лист1",
        "header_row": 1,
        "name_col": "Наименование товара",
        "photo_col": "Фото",
        "price_col": "Цена, ₽",
        "price_opt10_col": "От 10шт",
        "price_opt50_col": "От 50шт",
        "payment_col": "Безнал",
    },
    "supplier4": {
        "label": "BRATAN",
        "parser": "supplier4",
        "sheet_name": "Лена 25.05.24",
        "header_row": 0,
        "name_col": "Название",
        "stock_col": "Наличие",
        "pack_col": "упаковка (шт)",
        "weight_col": "вес 1 шт (кг)",
        "rrc_col": "РРЦ",
        "price_col": "от 1 уп",
        "own_price_col": "Своим",
        "photo_col": "Изображение",
    },
}
